class Text:
    def __int__(self):
        return

    @staticmethod
    def preprocessing(text):
        text = text.replace("</td>", "")
        text = text.replace("</em>", "")
        text = text.replace("</span>", "")
        text = text.replace("<span>", "")
        text = text.replace("</dd>", "")
        text = text.replace(",", "")
        text = text.replace("%", "")
        text = text.replace("+", "")
        text = text.replace("\n", "")
        text = text.replace("\t", "")
        text = text.replace("▲", "")
        text = text.replace("▼", "")
        text = text.replace("<td class=\"number\">", "")
        text = text.replace("<td class=\"no\">", "")
        text = text.replace("<td class=\"td\" id=\"quant\">", "")
        text = text.replace("<td class=\"td2\" id=\"amount\">", "")
        text = text.replace("<td class=\"imp_number\" id=\"now_value\">", "")
        text = text.replace("<td class=\"imp_txt\" id=\"change_rate\">", "")
        text = text.replace("<td class=\"imp_txt\" id=\"change_value\">", "")
        text = text.replace("<td class=\"rate_down\">", "")
        text = text.replace("<td class=\"rate_up\">", "")
        text = text.replace("<td class=\"tb_td3\">", "")
        text = text.replace("<td class=\"tb_td4\">", "")
        text = text.replace("<td class=\"tb_td5\">", "")
        text = text.replace("<td id=\"quant\">", "")
        text = text.replace("<td id=\"amount\">", "")
        text = text.replace("<dd class=\"dd\">개인<br/>", "")
        text = text.replace("<dd class=\"dd\">외국인<br/>", "")
        text = text.replace("<dd class=\"dd\">기관<br/>", "")
        text = text.replace("<dd class=\"dd\">전체<br/>", "")
        text = text.replace("<em id=\"now_value\">", "")
        text = text.replace("<span>억</span>", "")
        text = text.replace("<span class=\"dn\">", "")
        text = text.replace("<span class=\"up\">", "")
        text = text.replace("<span class=\"\">", "")
        text = text.replace("<span class="">", "")
        text = text.replace("<span class=\"value\">", "")
        text = text.replace("<span class=\"change\">", "")
        text = text.replace("<span class=\"point_status\">", "")
        text = text.replace("<span class=\"fluc\" id=\"change_value_and_rate\">", "")
        text = text.replace("<span class=\"tah p11 nv01\">", "")
        text = text.replace("<span class=\"tah p11 red01\">", "")
        text = text.replace("<span class=\"tah p11 nv02\">", "")
        text = text.replace("<span class=\"tah p11 red02\">", "")
        text = text.replace("<span class=\"tah p11 gray01\">", "")
        text = text.replace("<span class=\"tah p11 gray02\">", "")
        text = text.replace("<span class=\"tah p11\">", "")
        text = text.replace("<strong class=\"tah p11 nv01\">", "")
        text = text.replace("<strong class=\"tah p11 red01\">", "")
        text = text.replace("<strong class=\"tah p11 gray01\">", "")
        text = text.replace("<strong class=\"tah p11 nv02\">", "")
        text = text.replace("<strong class=\"tah p11 red02\">", "")
        text = text.replace("<strong class=\"tah p11 gray02\">", "")
        text = text.replace("<strong class=\"tah nv01\">", "")
        text = text.replace("<strong class=\"tah red01\">", "")
        text = text.replace("<strong class=\"tah gray01\">", "")
        text = text.replace("<strong class=\"tah nv02\">", "")
        text = text.replace("<strong class=\"tah red02\">", "")
        text = text.replace("<strong class=\"tah gray02\">", "")
        text = text.replace("<strong class=\"nv01\">", "")
        text = text.replace("<strong class=\"red01\">", "")
        text = text.replace("<strong class=\"gray01\">", "")
        text = text.replace("<strong class=\"nv02\">", "")
        text = text.replace("<strong class=\"red02\">", "")
        text = text.replace("<strong class=\"gray02\">", "")
        text = text.replace("<strong class=\"\">", "")
        text = text.replace("</strong>", "")
        return text